#include "tests/harness/proto/base/bool.pb.h"
#include "tests/harness/proto/base/bool.pb.validate.h"
#include "tests/harness/proto/base/bytes.pb.h"
#include "tests/harness/proto/base/bytes.pb.validate.h"
#include "tests/harness/proto/base/enums.pb.h"
#include "tests/harness/proto/base/enums.pb.validate.h"
#include "tests/harness/proto/base/maps.pb.h"
#include "tests/harness/proto/base/messages.pb.h"
#include "tests/harness/proto/base/messages.pb.validate.h"
#include "tests/harness/proto/base/numbers.pb.h"
#include "tests/harness/proto/base/numbers.pb.validate.h"
#include "tests/harness/proto/base/oneofs.pb.h"
#include "tests/harness/proto/base/oneofs.pb.validate.h"
#include "tests/harness/proto/base/repeated.pb.h"
#include "tests/harness/proto/base/repeated.pb.validate.h"
#include "tests/harness/proto/base/strings.pb.h"
#include "tests/harness/proto/base/strings.pb.validate.h"
#include "tests/harness/proto/base/wkt_any.pb.h"
#include "tests/harness/proto/base/wkt_any.pb.validate.h"
#include "tests/harness/proto/base/wkt_duration.pb.h"
#include "tests/harness/proto/base/wkt_duration.pb.validate.h"
#include "tests/harness/proto/base/wkt_nested.pb.h"
#include "tests/harness/proto/base/wkt_nested.pb.validate.h"
#include "tests/harness/proto/base/wkt_timestamp.pb.h"
#include "tests/harness/proto/base/wkt_wrappers.pb.h"
#include "tests/harness/proto/base/wkt_wrappers.pb.validate.h"

int main() { return EXIT_SUCCESS; }
