name: ci

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: protoc-gen-validate:${{ github.sha }}
      - name: Run
        run: |
          docker run --rm protoc-gen-validate:${{ github.sha }} ci
